<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class ClientSeeder extends Seeder
{
    public function run(): void
    {
        $clients = [
            [
                'full_name'      => 'Juan dela Cruz',
                'email'          => 'juan@example.com',
                'password'       => 'Client@1234',
                'age'            => 22,
                'gender'         => 'male',
                'address'        => 'Brgy. Sala, Cabuyao, Laguna',
                'contact_number' => '09201234567',
                'role'           => 'client',
                'is_verified'    => true,
            ],
            [
                'full_name'      => 'Maria Santos',
                'email'          => 'maria@example.com',
                'password'       => 'Client@1234',
                'age'            => 25,
                'gender'         => 'female',
                'address'        => 'Brgy. Mamatid, Cabuyao, Laguna',
                'contact_number' => '09209876543',
                'role'           => 'client',
                'is_verified'    => true,
            ],
            [
                'full_name'      => 'Pedro Reyes',
                'email'          => 'pedro@example.com',
                'password'       => 'Client@1234',
                'age'            => 30,
                'gender'         => 'male',
                'address'        => 'Brgy. Baclaran, Cabuyao, Laguna',
                'contact_number' => '09205551234',
                'role'           => 'client',
                'is_verified'    => true,
            ],
            [
                'full_name'      => 'Ana Reyes',
                'email'          => 'ana@example.com',
                'password'       => 'Client@1234',
                'age'            => 23,
                'gender'         => 'female',
                'address'        => 'Brgy. Pittland, Cabuyao, Laguna',
                'contact_number' => '09181234568',
                'role'           => 'client',
                'is_verified'    => true,
            ],
            [
                'full_name'      => 'Carlo Mendoza',
                'email'          => 'carlo@example.com',
                'password'       => 'Client@1234',
                'age'            => 27,
                'gender'         => 'male',
                'address'        => 'Brgy. Diezmo, Cabuyao, Laguna',
                'contact_number' => '09178765432',
                'role'           => 'client',
                'is_verified'    => true,
            ],
            [
                'full_name'      => 'Sofia Lim',
                'email'          => 'sofia@example.com',
                'password'       => 'Client@1234',
                'age'            => 21,
                'gender'         => 'female',
                'address'        => 'Brgy. Banay-Banay, Cabuyao, Laguna',
                'contact_number' => '09991234569',
                'role'           => 'client',
                'is_verified'    => true,
            ],
            [
                'full_name'      => 'Mark Flores',
                'email'          => 'mark@example.com',
                'password'       => 'Client@1234',
                'age'            => 31,
                'gender'         => 'male',
                'address'        => 'Brgy. Butong, Cabuyao, Laguna',
                'contact_number' => '09051234570',
                'role'           => 'client',
                'is_verified'    => true,
            ],
            [
                'full_name'      => 'Jasmine Cruz',
                'email'          => 'jasmine@example.com',
                'password'       => 'Client@1234',
                'age'            => 26,
                'gender'         => 'female',
                'address'        => 'Brgy. Marinig, Cabuyao, Laguna',
                'contact_number' => '09261234571',
                'role'           => 'client',
                'is_verified'    => true,
            ],
            [
                'full_name'      => 'Ryan Bautista',
                'email'          => 'ryan@example.com',
                'password'       => 'Client@1234',
                'age'            => 24,
                'gender'         => 'male',
                'address'        => 'Brgy. Niugan, Cabuyao, Laguna',
                'contact_number' => '09151234572',
                'role'           => 'client',
                'is_verified'    => true,
            ],
            [
                'full_name'      => 'Camille Garcia',
                'email'          => 'camille@example.com',
                'password'       => 'Client@1234',
                'age'            => 29,
                'gender'         => 'female',
                'address'        => 'Brgy. Sala, Cabuyao, Laguna',
                'contact_number' => '09221234573',
                'role'           => 'client',
                'is_verified'    => true,
            ],
            [
                'full_name'      => 'Lester Torres',
                'email'          => 'lester@example.com',
                'password'       => 'Client@1234',
                'age'            => 22,
                'gender'         => 'male',
                'address'        => 'Brgy. Mamatid, Cabuyao, Laguna',
                'contact_number' => '09331234574',
                'role'           => 'client',
                'is_verified'    => true,
            ],
            [
                'full_name'      => 'Alyssa Villanueva',
                'email'          => 'alyssa@example.com',
                'password'       => 'Client@1234',
                'age'            => 28,
                'gender'         => 'female',
                'address'        => 'Brgy. Baclaran, Cabuyao, Laguna',
                'contact_number' => '09441234575',
                'role'           => 'client',
                'is_verified'    => true,
            ],
            [
                'full_name'      => 'Dennis Aquino',
                'email'          => 'dennis@example.com',
                'password'       => 'Client@1234',
                'age'            => 33,
                'gender'         => 'male',
                'address'        => 'Brgy. Pittland, Cabuyao, Laguna',
                'contact_number' => '09551234576',
                'role'           => 'client',
                'is_verified'    => true,
            ],
            [
                'full_name'      => 'Kristine Ramos',
                'email'          => 'kristine@example.com',
                'password'       => 'Client@1234',
                'age'            => 25,
                'gender'         => 'female',
                'address'        => 'Brgy. Diezmo, Cabuyao, Laguna',
                'contact_number' => '09661234577',
                'role'           => 'client',
                'is_verified'    => true,
            ],
            [
                'full_name'      => 'Miguel Santos',
                'email'          => 'miguel@example.com',
                'password'       => 'Client@1234',
                'age'            => 20,
                'gender'         => 'male',
                'address'        => 'Brgy. Banay-Banay, Cabuyao, Laguna',
                'contact_number' => '09771234578',
                'role'           => 'client',
                'is_verified'    => true,
            ],
        ];

        foreach ($clients as $client) {
            User::firstOrCreate(['email' => $client['email']], $client);
        }
    }
}
